import {
  CheckCircleIcon,
  StoreIcon,
  ArrowLeftIcon,
  RewardIcon,
  OrganizationIcon,
  ChartHistogramGrowthIcon,
} from "@shopify/polaris-icons";

export const PRICING_PLANS = [
  {
    id: "free",
    title: "Free",
    subtitle: "Free forever",
    monthlyPrice: 0,
    yearlyPrice: 0,
    disabled: true,
    icon: StoreIcon,
    features: [
      "Cart theming",
      "Floating cart button",
      "In-cart discount box",
      "Sticky bar ATC widget",
      "Multi-language support",
      "In-cart terms check box",
      "Custom CSS & JS support",
      "Customisable cart drawer",
    ],
  },
  {
    id: "standard",
    title: "Standard",
    subtitle: "Fixed pricing based on Shopify plan",
    monthlyPrice: 15,
    yearlyPrice: 150, // 2 months free
    icon: RewardIcon,
    features: [
      "Everything in Free plan",
      "In-cart upsell",
      "Cart progress bar",
      "One-click upsell",
      "Free gift campaigns",
      "Cart announcement bar",
      "Cart countdown timer",
      "Priority chat support",
      "Volume discount campaign",
      "Buy X Get Y campaigns",
    ],
  },
  {
    id: "grow",
    title: "Grow",
    subtitle: "For stores using Shopify Plan",
    monthlyPrice: 29,
    yearlyPrice: 290,
    icon: ChartHistogramGrowthIcon,
    features: [
      "Unlimited campaigns",
      "Free gift campaigns",
      "Buy X get Y campaign",
      "Urgency timers & cart announcements",
      "Volume discount campaigns",
      "One-click upsell campaign",
      "Up to 5000 orders per month",
    ],
  },
  {
    id: "enterprise",
    title: "Enterprise",
    subtitle: "For stores using Advanced Shopify Plan",
    monthlyPrice: 59,
    yearlyPrice: 590,
    icon: OrganizationIcon,
    features: [
      "Unlimited campaigns",
      "Free gift campaigns",
      "Buy X get Y campaign",
      "Urgency timers & cart announcements",
      "Volume discount campaigns",
      "One-click upsell campaign",
      "Up to 5000 orders per month",
    ],
  },
];
