export const PRICING_PLANS = [
  {
    id: "free",
    title: "Free",
    subtitle: "Free forever",
    price: 0,
    disabled: true,
    features: [
      "Cart theming",
      "Floating cart button",
      "In-cart discount box",
      "Sticky bar ATC widget",
      "Multi-language support",
      "In-cart terms check box",
      "Custom CSS & JS support",
      "Customisable cart drawer",
    ],
  },
  {
    id: "standard",
    title: "Standard",
    subtitle: "Fixed pricing based on Shopify plan",
    price: 15,
    features: [
      "Everything in Free plan",
      "In-cart upsell",
      "Cart progress bar",
      "One-click upsell",
      "Free gift campaigns",
      "Cart announcement bar",
      "Cart countdown timer",
      "Priority chat support",
      "Volume discount campaign",
      "Buy X Get Y campaigns",
    ],
  },
  {
    id: "grow",
    title: "For Grow",
    subtitle: "For stores using Shopify Plan",
    price: 29,
    features: [
      "Unlimited campaigns",
      "Free gift campaigns",
      "Buy X get Y campaign",
      "Urgency timers & cart announcements",
      "Volume discount campaigns",
      "One-click upsell campaign",
      "Up to 5000 orders per month",
    ],
  },
  {
    id: "advanced",
    title: "Advanced Shopify",
    subtitle: "For stores using Advanced Shopify Plan",
    price: 59,
    features: [
      "Unlimited campaigns",
      "Free gift campaigns",
      "Buy X get Y campaign",
      "Urgency timers & cart announcements",
      "Volume discount campaigns",
      "One-click upsell campaign",
      "Up to 5000 orders per month",
    ],
  },
];
